### ISSUE TITLE
Failed to extract

### ISSUE THREAD

**Issue by aymende7** [Asia81/HackingToolkit3DS#1]
Please wait, extraction in progress...

Extraction done!

Appuyez sur une touche pour continuer...
but the rom doesn't extracted
i have Ocarina of time 3D 
decrypted 
Cia format

**Comment by Asia81** [comment]
Are you sure to have installed the SetupXX.exe file first?
Are you sure to not write the extention while writing the name, when asking?
Are you sure that the 3DS|CIA doesn't contain any spaces or special characters?
Are you sure your file is correctly decrypted by Decrypt9?
Is your Windows a 32 or 64b?

**Comment by aymende7** [comment]
Q:Are you sure to have installed the SetupXX.exe file first?
+Yes
Q:Are you sure to not write the extention while writing the name, when asking?
+Yes
Q:Are you sure that the 3DS|CIA doesn't contain any spaces or special characters?
+Yes
Q:Are you sure your file is correctly decrypted by Decrypt9?
+Yes
Q:Is your Windows a 32 or 64b?
+I have windows 10 32bit
And i formatted my computer to Windows 7 32bit and it works now great tool :)
sorry for disturbing you
It ctrtool fault 
it doesn't work in windows 10 32bit 
Thanks for replying 
Sorry for bad English :)

**Comment by Asia81** [comment]
I added the support for 32bits Windows (I found a CtrTool and Makerom 32bits build).
I tried in a Windows 10 32 bits (using a virtual machine) extraction and rebuild are fine.
Wait ~10mns until I upload the V8 and you should be ok.

**Comment by Asia81** [comment]
Try, it should be ok now.

**Comment by aymende7** [comment]
Cool!
Ok i will try it soon when i update to windows 10 
Thanks again :D
