### ISSUE TITLE
Extraction does nothing

### ISSUE THREAD

**Issue by GhaleonZ** [Asia81/HackingToolkit3DS#2]
I have tried to repeatedly extract a decrypted CIA of Fire Emblem Fates: Special Edition. There is no error given by Decrypt9.

I run HackingToolkit3ds. Put in CE, then the name of my CIA file. (Special.cia, without the .cia, of course)
It says the following:

Please wait, extraction in progress...
Extraction done!
Press any key to continue...

This happens in less than 20 seconds, with no visible folders appearing in the PackHack folder.

**Comment by Asia81** [comment]
Are you sure to have installed the SetupXX.exe file first?
Are you sure to not write the extention while writing the name, when asking?
Are you sure that the 3DS|CIA doesn't contain any spaces or special characters?
Are you sure your file is correctly decrypted by Decrypt9?
Is your Windows a 32 or 64b?

**Comment by GhaleonZ** [comment]
Yeah, I did all that stuff. I figured out the problem after a lot of searching.

Looks like I'm screwed on being able to do anything with FE-Fates
until I can get a 64-bit PC.

Which sucks because I wanted to explore the smaller CIAs for the
cipher/amiibo/boss characters. But I have no way to extract the files
from within the CIA.

**Comment by Asia81** [comment]
Is you CIA extracted fine now?

**Comment by GhaleonZ** [comment]
No. I can't do anything because there is no 32-bit CTRTool. Something
about it only working in 64-bit because of games requiring a ton of
RAM to extract. And my PC is 32-bit.
