### ISSUE TITLE
Setup requires admin access

### ISSUE THREAD

**Issue by mariomadproductions** [Asia81/HackingToolkit3DS#6]
Surely the setup exe just extracts some files? Why does it need admin access?

**Comment by aymende7** [comment]
Adding files to c:/program files needs admin access :)

**Comment by mariomadproductions** [comment]
Could the option to install it to a different folder be added?

**Comment by Asia81** [comment]
No, sorry.

**Comment by mariomadproductions** [comment]
Why not?

**Comment by Asia81** [comment]
Because.

**Comment by mariomadproductions** [comment]
...?

**Comment by mariomadproductions** [comment]
It isn't called github because you are are meant to act like a git.

**Comment by mariomadproductions** [comment]
https://github.com/Asia81/HackingToolkit9DS/issues/12#issuecomment-338786113
